spring.application.name=TinBall-backend

# Configuración dinámica de Base de Datos
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tinball}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Puerto dinámico (Render lo necesita)
server.port=${PORT:8080}